/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LCodigoRouteImport } from './routes/l.$codigo'
import { Route as PNumeroRouteImport } from './routes/p.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LCodigoRoute = LCodigoRouteImport.update({
  id: '/l/$codigo',
  path: '/l/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const PNumeroRoute = PNumeroRouteImport.update({
  id: '/p/$numero',
  path: '/p/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/l/$codigo': typeof LCodigoRoute
  '/p/$numero': typeof PNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/l/$codigo': typeof LCodigoRoute
  '/p/$numero': typeof PNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/l/$codigo': typeof LCodigoRoute
  '/p/$numero': typeof PNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/auth' | '/l/$codigo' | '/p/$numero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/l/$codigo' | '/p/$numero'
  id: '__root__' | '/' | '/admin' | '/auth' | '/l/$codigo' | '/p/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LCodigoRoute: typeof LCodigoRoute
  PNumeroRoute: typeof PNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$codigo': {
      id: '/l/$codigo'
      path: '/l/$codigo'
      fullPath: '/l/$codigo'
      preLoaderRoute: typeof LCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$numero': {
      id: '/p/$numero'
      path: '/p/$numero'
      fullPath: '/p/$numero'
      preLoaderRoute: typeof PNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LCodigoRoute: LCodigoRoute,
  PNumeroRoute: PNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
